### ISSUE TITLE
Avoid reference to `hs-bindgen-root` in errors

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#855]
Something like this:

```
[Error  ] [Libclang ] hs-bindgen-root.h:1:10: fatal error: 'foo.h' file not found
```

is confusing. This is a regression, introduced in #792, when we removed `ParseCHeadersException`.
